spring.datasource:
  url: jdbc:postgresql://localhost:5432/petproject
  username: petproject
  password: petproject

spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate:
    jdbc.lob.non_contextual_creation: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

petproject.jwt:
  secret: secret
  expiration: 0